name: 'Publish: Flutter Builds'

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Place tag in environment
        run: |
          echo "SOURCE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Write tag version to pubspec.yaml
        run: |
          sed -i "s/^version:.*/version: ${SOURCE_TAG#v}/" pubspec.yaml

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1

      - name: Install Flutter SDK
        run: fvm install

      - name: Activate Flutter SDK
        run: fvm use --skip-pub-get

      - name: Get depedencies
        run: fvm flutter pub get

      - name: Write secret files
        run: |
          echo "${{ secrets.FLUTTER_ENV_BASE64 }}" | base64 -d > ./.env
          echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 -d > ./android/app/google-services.json
          echo "${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}" | base64 -d > ./android/key.properties
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./android/app/keystore.jks

      - name: Build for web
        run: fvm flutter build web --dart-define=PRODUCTION_LOGGING=true
        # run: fvm flutter build web --profile --source-maps --dart-define=Dart2jsOptimization=O0 --dart-define=PRODUCTION_LOGGING=true

      - name: Upload web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Build APK for Android
        run: fvm flutter build apk

      - name: Build App Bundle for Android
        run: fvm flutter build appbundle

      - name: Upload APK to release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/app/outputs/flutter-apk/app-release.apk"]'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
